# Generated by Django 4.1.5 on 2023-02-07 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('categorie', models.CharField(choices=[('musique', 'musique'), ('cinema', 'cinema'), ('sport', 'sport')], max_length=8)),
                ('state', models.BooleanField(default=False)),
                ('nbrParticipants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='le nbr de participon doit etre positive')])),
                ('dateEvent', models.DateField(validators=[events.models.isDateValid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participationdate', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
