# Generated by Django 4.1.5 on 2023-02-07 15:05

import datetime
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='la date et invalide',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, validators=[events.models.istitleValid]),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('dateEvent__gte', datetime.datetime(2023, 2, 7, 16, 5, 3, 244602))), name='la date et invalide'),
        ),
    ]
