# Generated by Django 4.1.5 on 2023-02-07 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_la date et invalide_alter_event_title_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='la date et invalide',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('dateEvent__gte', datetime.datetime(2023, 2, 7, 16, 11, 7, 121254))), name='la date et invalide'),
        ),
    ]
